### ISSUE TITLE
installation issue revisited

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#15] opened 2016-08-29 10:57 UTC
hello 
I installed code block and I copy and paste the 
code 
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

int main( int argc, char* argv[] )
{
    // Load in test image
    Mat image = imread("/home/koj/123jpeg", IMREAD_GRAYSCALE);
    imshow("original", image); waitKey(0);

    return 0;
}

and went to" build option" as recommended by steven and "linker setting" ->"other linker options" ->I typed in the "`pkg-config opencv --libs`"
and started build and run 
the result was hello world inthe console screen which I could close by entering some key.
![ubuntu 64-bit 3 -2016-08-29-19-48-46](https://cloud.githubusercontent.com/assets/21294401/18049378/d8a31d48-6e22-11e6-86b8-bf6fd3cc0bf0.png)

1.is that right???
2.where can I use the command  $ g++ test.cpp -o test `pkg-config opencv --libs'?

it is very frustrating .
3.what  project should I make to begin with? opencv project or console application project.
4.and why does the project file name becomes cbp instead of cpp?

**Comment by StevenPuttemans** [comment] 2016-08-29 11:05
Wow wait you are mixing so much stuff up... let me refrain. As said tons of times before, go read a tutorial on setting up codeblocks. It seems you got there, but you are missing some major things, like that `g++` is for example...

Answers

1. Yes this is right up till now. As confirmed by the code, the process was terminated correctly (status 0).
2. You don't need that, since you are using a developing environment now. Basically when you hit the build button, your environment compiles such a command and executes that for your. Take a look at all the log tabs, somewhere will be an identical command like the `g++` one we provided. The `g++` command is if you want to build cpp code from the console window, without an IDE.
3. I always start from a clean console application project. The opencv one in there is not set up correctly in my honest opinion.
4. You are mixing stuff up. The *.cbp file is the project file of codeblocks, containing the knowledge to reconstruct your project when closing and opening the application. There will still be a `main.cpp` file inside your source folder, containing your actual code.

But please, these questions are mainly focussing on getting your system set up, not about real actual issues with our repository. You should try to solve them with the vast majority of information on the WWW.

**Comment by mecccu** [comment] 2016-08-29 11:56
thanks for your kind reply steven.
you are right may be my question and problems are not central to opencv.
just an environmental issue.
If I had to figure it out with googling it would cost so many times like me who majored medicine not computer programming.
thanks for helping me installing.
have a nice day 
bye

**Closed** 2016-08-29 11:57 UTC
