### ISSUE TITLE
axus xtion pro cannot be stopped in chapter 1 infravision.

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#20] opened 2016-12-03 10:54 UTC
hello again
I installed asus xtion pro .
one thing i noticed was the command line of the book regarding usb3.0 and usb2.0 problem did not work.
i tried wine cmd with running the usbupdate.bat file and it worked.
And another issue was installing openni2 the installation guide maybe outdated that openjdk-6-jdk nolonger exist and openjdk-8-jre was what i have done.
and when i added all the library files in the linker setting I added 7 which was in the folder which was pointed by the author in the book.
and included the search directory two of them openni2 and opencv .
and ran the infravision and it run good
but when i want to exit the program so i clicked the red button on the infrared camera screen.
but it reappeared soon and the console was saying some error message about the usb priority problem.
I did it both on the vmshare and ubutu alone computer but both had exactly the same problem.
when i turned off the console screen the infrared filming screen and console was gone but the red light of the xtion pro which i think is indicating the ir light is emitting is stlll on.
So i had to pull off the usb cord from my computer to trun off those red light of asus xtion pro.
do you know why this happens?
i attached some photo
![dsc_0291](https://cloud.githubusercontent.com/assets/21294401/20858869/b01bfa30-b903-11e6-8f7b-584773c89daf.JPG)
![dsc_0292](https://cloud.githubusercontent.com/assets/21294401/20858871/bcc433d8-b903-11e6-8b1e-90824716559e.JPG)

**Comment by mecccu** [comment] 2016-12-03 10:57
red button means exit button "x" button at the menubar of the infravision screen

**Comment by JoeHowse** [comment] 2016-12-03 13:49
> one thing i noticed was the command line of the book regarding usb3.0 and usb2.0 problem did not work.
> i tried wine cmd with running the usbupdate.bat file and it worked.

As the book says, the Asus firmware update script is for Windows.  But I'm glad to hear that it works in the wine Windows emulator too.

> And another issue was installing openni2 the installation guide maybe outdated that openjdk-6-jdk nolonger exist and openjdk-8-jre was what i have done.

This sounds like an issue with the instructions on the [OpenNI2 GitHub page](https://github.com/occipital/openni2), so please report it there instead, so that the issue is seen by someone who can fix it.

> but when i want to exit the program so i clicked the red button on the infrared camera screen.
but it reappeared soon

As described on page 25-26 of the book, you need to press any keyboard key to exit this program.  Please read the instructions in the book fully before posting issues.

> some error message about the usb priority problem.

The warning seems to be benign; there was just a momentary interruption in the USB transfer when you tried to close the window.

In the future, please post error/warning messages in the text instead of as screenshots.  This will make your posts easier to read and to search.

> when i turned off the console screen the infrared filming screen and console was gone but the red light of the xtion pro which i think is indicating the ir light is emitting is stlll on.

When you quit the console window, you killed the program prematurely and this is probably why the camera did not shut down properly.  Quit the program by pressing any keyboard key instead.

Closing.

**Closed by JoeHowse** 2016-12-03 13:49 UTC
