### ISSUE TITLE
blinking eye program is not working

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#18] opened 2016-11-28 11:20 UTC
hello 
i bought playstation eye and inserted to my notebook which has vmware pro12 and ubuntu 14.04 installed.
I cannot find how can i install my playstation eye driver in this book to my ubuntu so i just connected to my usb slot and i cannot figure out it is working or not.
and I copied the cpp file of the blinking eye source code and then I made a console project at codeblocks.
and then build and run .
First time it made an error so I add to linker setting the `pkg-config opencv --libs`
and then it made no error

when i ran it first time it made a blank x terminal with no message i waited but nothing appeared.
So I quit the terminal by clicking  x button in the terminal window and when I go back to the project folder there was a slowmo video file.but when i played it says it is empty .
So I thought there is a problem with the playstation eye installation.
So I searched google and find out following site
http://oftw.wikidot.com/install-ps3-eye-camera-in-ubuntu
but it did not worked at second the line
"sudo patch -p1 < ps3eyeMT-2.6.31-10-generic.patch
only patch the driver in drivers/media/video/gspca/ov534.c"
I could not understand the meaning of "only patch the driver ..."
So it made an error at console window and i gave up following that method.
So I came back to my codeblock and run again this time the following attached screen appeared at the window.
So I changed the frame rate in the source code to 120 but this time again the same window appeared.
how can I install the playstation eye driver to my computer and why does this slowmo video is empty?
how do i know my playstation eye is working in ubuntu.?
what is the playstation eye dial at the lens functions is it a power button?
![dsc_0225](https://cloud.githubusercontent.com/assets/21294401/20666547/0f59aefc-b5a8-11e6-813a-0e894043d11f.JPG)

**Comment by StevenPuttemans** [comment] 2016-11-28 11:39
Hello @mecccu. First of all thank you for buying the book and having a go at some of the code. I would ask @JoeHowse to take a look at this, since he has a playstation eye available and could thus debug your problem better then I do.

**Comment by mecccu** [comment] 2016-11-28 11:42
thanks for reply
when i played slowmo.avi it says
"an error occured" and
"The specified movie could not be found".

**Comment by JoeHowse** [comment] 2016-11-28 14:15
Hi @mecccu!  Thanks for reading the book.  There are several potential issues here, so I will go through them one by one.

> i bought playstation eye and inserted to my notebook which has vmware pro12 and ubuntu 14.04 installed.

Ubuntu 14.04 should already have a version of the PS3 Eye driver that supports up to 125 FPS.  You don't need to install it.  I don't know whether it will work with vmware.  Virtual machines sometimes have problems with some drivers.

To test whether the driver is working, plug in the PS3 Eye, open the Cheese application (which comes with Ubuntu), and try to take some pictures with the webcam.  If you can see the live video preview and take pictures in Cheese, the driver is working.  Please let me know the result of this test.

> when i ran it first time it made a blank x terminal with no message i waited but nothing appeared.

This sounds like the correct behavior. `unblinking_eye` silently captures frames until it reaches the number of frames defined in this line of code:

```
const unsigned int numFrames = 3750;
```

If you want it to finish more quickly, you can use some smaller number.  For example, `const unsigned int numFrames = 625` would be 5 seconds at 125 FPS.

> So I quit the terminal by clicking x button in the terminal window and when I go back to the project folder there was a slowmo video file.but when i played it says it is empty .

It seems that you terminated `unblinking_eye` prematurely, so it did not successfully record the video file.  Please retry, let the program run to completion, and tell me the result.

You've reported that your attempt to patch the driver failed, but it sounds as if it failed early, so no changes actually got installed.  Let's leave the driver alone until we've explored other options.

> So I changed the frame rate in the source code to 120

This should be 125.

> what is the playstation eye dial at the lens functions is it a power button?

It is a zoom function.  The lens has a wide-angle mode and a narrow-angle mode.

**Comment by mecccu** [comment] 2016-11-28 15:38
cheese is installed so i opened it but all of its button is not activated nothing can be clicked i attached the photo
![dsc_0237](https://cloud.githubusercontent.com/assets/21294401/20674381/142a9968-b5cc-11e6-9892-db8f92ce1f5d.JPG)

**Comment by mecccu** [comment] 2016-11-28 15:39
i plug in the playstaion eye and opened vmshare and ubuntu and cheese successively.
but the result is as above photo

**Comment by JoeHowse** [comment] 2016-11-28 15:50
In this case, it seems that the driver is not working. Could you try it with a fresh installation of Ubuntu 16.04? If a fresh installation of Ubuntu 16.04 doesn't work in VMware, then the problem is probably specific to VMware.

**Comment by mecccu** [comment] 2016-11-28 16:14
![dsc_0242](https://cloud.githubusercontent.com/assets/21294401/20675843/12ec454c-b5d1-11e6-8744-f37a12ccbd7f.JPG)
i added at the camera which seems to be playstation eye at the  vmware removable device  tab and when i opened cheese i could see the camera working but when i changed the cheese's mode to video it closed unexpectedly with error.
so i went back to codeblock and then pasted the original source code of blinking eye and then build and run this time thebelow error message was displayed at the console window.
![dsc_0240](https://cloud.githubusercontent.com/assets/21294401/20675815/f633df00-b5d0-11e6-8054-896028695d47.JPG)
![dsc_0239](https://cloud.githubusercontent.com/assets/21294401/20675825/04155e64-b5d1-11e6-9d60-13fbd9a9759e.JPG)

**Comment by mecccu** [comment] 2016-11-28 16:15
after running blinking eye it shows an error message videoio erro v4l index 0 is not correct?
what does it mean

**Comment by mecccu** [comment] 2016-11-28 16:24
after changing index to 1 following error message appeared just like the first 
![dsc_0243](https://cloud.githubusercontent.com/assets/21294401/20676273/88359d98-b5d2-11e6-8a27-1c15ec0fc1d1.JPG)

**Comment by JoeHowse** [comment] 2016-11-28 17:40
There are still several issues here, so I'll address them one-by-one again.

> when i changed the cheese's mode to video it closed unexpectedly with error

This suggests that there is still some camera driver issue, or perhaps a video codec issue that causes video recording to fail.  What is the error message?  Are you still using OpenCV 14.04?

> after running blinking eye it shows an error message videoio erro v4l index 0 is not correct?
what does it mean

It seems that your system has assigned device index 1 (not 0) to the PS3 Eye.  This may vary depending on whether you have other webcams plugged in.

> VIDEOIO ERROR V3L2: setting property #9 is not supported

Are you using OpenCV 2.4.x?  (If you used the packages in the Ubuntu 14.04 standard repositories, you have OpenCV 2.4.x.)  For this book, you need OpenCV 3.x.  Please see our [OpenCV 3 installation guide for Linux](https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/installation_tutorials/installation_linux.md).

**Comment by mecccu** [comment] 2016-11-29 01:24
i followed all your installation guide and the blinking eye source code has 
#include <stdio.h>
#include <time.h>

#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>

which seems to use opencv2
and also i cannot update ubuntu 16.04
at the console screen i updated but gui screen still shows ubuntu 14 
do you know how to update ubuntu 14 lts to ubuntu 16 gui?

**Comment by mecccu** [comment] 2016-11-29 01:52
I think VIDEOIO ERROR V4L2: setting property #9 is not supported means that
const unsigned int numFrames = 3750;
 this part is not supported I think this error can be overcomed if i change the number the real problem I think is the next part which is very long which says
opencv error assertion failed ~~

**Comment by mecccu** [comment] 2016-11-29 01:55
is there a gui version of ubuntu 16?
how can i update form ubuntu 14.04 lts gui screen to ubuntu 16 gui ?

**Comment by mecccu** [comment] 2016-11-29 01:56
but i dont think the ubuntu version is the problem i think the opencv connection with my project and camera has problem.

**Comment by JoeHowse** [comment] 2016-11-29 01:58
All of the book's projects require OpenCV 3.  The `opencv2` headers are the C++ API and the `opencv` headers are the older C API; these header names don't refer to the OpenCV version number.

Just to clarify, I'd like to ask:

1. Were you previously using OpenCV 2.x?
2. Are you now using OpenCV 3.x?
3. If the answers to [1] and [2] are "yes", did any of the errors get resolved when you updated to OpenCV 3.x?

Note that you should uninstall OpenCV 2.x if you previously installed it.

> I think VIDEOIO ERROR V4L2: setting property #9 is not supported means that
> const unsigned int numFrames = 3750;
> this part is not supported

No, you are incorrect.  The error means that a particular property was not found, and this property was introduced in OpenCV 3.x.  That is why I believe you may be using OpenCV 2.x.

> is there a gui version of ubuntu 16?

Yes.

> how can i update form ubuntu 14.04 lts gui screen to ubuntu 16 gui ?

For Ubuntu updates, use the Software Updater application and if you encounter problems, please try an Ubuntu support forum such as [Ask Ubuntu](https://askubuntu.com/).

The drivers are most likely to work in a fresh, non-VM installation of Ubuntu 16.04.

**Comment by mecccu** [comment] 2016-11-29 02:01
thanks i am a newcomer to opencv so i dont think i have installed opencv2
how do i check there is opencv 2 in my ubuntu?
and about updating to ubuntu 16.04 my software updater updated all the updates but still the gui screen shows 14.04

**Comment by mecccu** [comment] 2016-11-29 02:04
i found that in the opencv  folder there is include folder inside there is opencv2 folder which i think is installed by this books installation process should i remove it?

**Comment by JoeHowse** [comment] 2016-11-29 02:30
OpenCV 3 Blueprints is intended as an advanced book on OpenCV and computer vision, so for a newcomer it will be a steep learning curve.

> i found that in the opencv folder there is include folder inside there is opencv2 folder which i think is installed by this books installation process should i remove it?

No, do not remove it.

One way to check the OpenCV version is to open Terminal and run these commands:

```
$ python
>>> import cv2
>>> cv2.__version__
```

Here, we are running the Python interactive interpreter, we're importing the `cv2` package (which is OpenCV), and we're asking it what its version number is.  It will print out something like this:

```
>>> '3.1.0'
```

This is the OpenCV version number, so let me know what it is.  After you have this information, you can quit the Python interactive interpreter:

```
>>> quit()
```

And close Terminal.

**Comment by mecccu** [comment] 2016-11-29 03:43
![dsc_0246](https://cloud.githubusercontent.com/assets/21294401/20695706/5f9e16e4-b631-11e6-88c5-98f41e6144f9.JPG)
![dsc_0245](https://cloud.githubusercontent.com/assets/21294401/20695707/5fa271bc-b631-11e6-8dcc-d98278e040c0.JPG)

**Comment by mecccu** [comment] 2016-11-29 03:45
when built in web cam is connected to my virtual machine qt v4l2 test does not activate at all.
so i disconnected built in webcam and connect only the playstation eye and then the qt v4l2 test screen shows the above and the driver specification is alright in my sight.

**Comment by mecccu** [comment] 2016-11-29 03:48
and about upgrading ubuntu i already done following command successfully on my console screen but when i power up ubuntu 14.04 gui appears again.
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo do-release-upgrade

**Comment by JoeHowse** [comment] 2016-11-29 04:54
> when built in web cam is connected to my virtual machine qt v4l2 test does not activate at all.

I strongly suspect that v4l2 and/or libv4l are broken (or at least very buggy) on your VM.  As I've mentioned before, I recommend that you do not use a VM, and that you start over with a fresh installation of Ubuntu 16.04 as a real machine (not a VM).  I don't think I can provide further help with your VM environment.

If you do want to keep trying with your VM environment, I've included a few more notes below.  These may or may not help; I think the underlying problem is with the VM.

As I mentioned before, you should try [Ask Ubuntu](https://askubuntu.com/) if you have general questions about Ubuntu upgrades or other Ubuntu features.

Based on the Python output, you do have OpenCV 3.1.0 installed.  This is good, as it suggests that the steps in the installation tutorial worked (mostly or fully).

The error `VIDEOIO ERROR V3L2: setting property #9 is not supported` could occur if `libv4l` is missing.  Do you have the `libv4l` package installed?  You check by running the following command in Terminal:

```
$ apt-cache policy libv4l
```

If you don't have it, you will see output like this:

```
libv4l:
  Installed: (none)
```

If you don't have it, you can install it like this:

```
$ sudo apt-get install libv4l
```

Then, rebuild OpenCV according to the setup tutorial, starting from the step "Running CMake to configure, build and install OpenCV 3".

**Comment by mecccu** [comment] 2016-11-29 05:31
Ok thanks.
If there is so many compatibility problems on programming why dont you just specify the exact version of your hardware and software you experimented opencv3 blueprint for the readers.
You can see no one can deal with all this issue of drivers ubuntu versions and virtual machine settings.
I bought vmware program 300dollars  and now i have to reinstall linux on new computer?
is there really an expert in linux who can manage this problem thoroughly?

**Comment by mecccu** [comment] 2016-11-29 09:24
From the new modules that are introduced, we only select BUILD_opencv_face, BUILD_opencv_xfeatures2d and BUILD_opencv_ximproc. All other new modules that are in red can be disabled. We do not need them for the book and they can only cause things to break down.
what does  from the new modules that are introduced means? all the lines checked ?
can you specify clearly what you are talking about should i check only 3 items after clicking configure tab?

**Comment by mecccu** [comment] 2016-11-29 09:25
I dont think the above question is about expertise  in linux its about writing clearly.

**Comment by mecccu** [comment] 2016-11-29 09:42
[ 16%] Building CXX object modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o
[ 16%] Linking CXX static library ../../lib/libopencv_core_pch_dephelp.a
[ 16%] Built target opencv_core_pch_dephelp
[ 16%] Generating precomp.hpp.gch/opencv_core_Debug.gch
[ 16%] Built target pch_Generate_opencv_core
Scanning dependencies of target opencv_core
[ 16%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/umatrix.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
modules/core/CMakeFiles/opencv_core.dir/build.make:90: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/src/umatrix.cpp.o' failed
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/umatrix.cpp.o] Error 4
CMakeFiles/Makefile2:1893: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
koj@ubuntu:~/opencv/build$

**Comment by mecccu** [comment] 2016-11-29 09:43
before updating ubuntu i could reach to hello world example
now the install process is making error even worse than before.

**Comment by StevenPuttemans** [comment] 2016-11-29 09:47
@mecccu I will have to agree with @JoeHowse on this and point the issue as being unrelated to our code, but being due to the fact that your virtual machine is not working correctly together with your actual hardware and OS. This is a big downside of virtual machines and can be avoided by installing an actual Ubuntu!

Furthermore, based on your conversation it is clear that OpenCV Blueprints is kind of over your head. The book clearly states that it is for advanced users with a profound knowledge of OpenCV and not for starters in the field.

This reasons made me decide to close this down. 

To have some final answers on your last remarks:

>> If there is so many compatibility problems on programming why dont you just specify the exact version of your hardware and software you experimented opencv3 blueprint for the readers.

Actually if you look at how many times the repository is cloned and how less issues we get here, it seems our explanation is quite correct and good to follow if one has some experience in programming with OpenCV and our hardware. Compatibility problems can never be avoided, but at the beginning of the book we have a clear overview of which parts are used and which versions of libraries...

>> I bought vmware program 300dollars and now i have to reinstall linux on new computer?

Sorry to hear that, but seriously, there are enough free of charge virtual machine systems out there. We cannot be held responsible for your decisions on this.

>> Is there really an expert in linux who can manage this problem thoroughly?

@JoeHowse has provided you with more solutions than possible, yet you seem to go around time each time again and not adressing them properly.

>> We do not need them for the book and they can only cause things to break down.
what does from the new modules that are introduced means? all the lines checked ?

Again, for mediate/experienced OpenCV users this means that
1) OpenCV contrib modules are the experimental branch and thus not always as stable as desired
2) Therefore we only select modules we actually need to avoid further problems
3) The CMAKE interface is quite standard in these days, so people should know how to use it. If not, look up a course on how to use CMAKE first

>> I dont think the above question is about expertise in linux its about writing clearly.

Actually ... wrong again ... this topic is clearly about a novice user of OpenCV trying to dig into advanced stuff first.

>> c++: internal compiler error: Segmentation fault (program cc1plus) Please submit a full bug report, with preprocessed source if appropriate.

This is an error of your compiler. Again writers of a book on OpenCV cannot be held responsible for that. You do not even need C++11 for this book at all...

**Closed by StevenPuttemans** 2016-11-29 09:47 UTC
